### ISSUE TITLE
Error when inference converted model

### ISSUE THREAD

**Issue by dummyedu** [NVIDIA-AI-IOT/torch2trt#21]
I create a custom model and register it in the module_test.py to test. 
It failed at native cuda. I guess the error is caused by torch.cat operation. 
But I can't get providence and no idea how to fix it.

The following is the log:

```
[TensorRT] ERROR: cuda/cudaConvolutionLayer.cpp (99) - Cudnn Error in computeScratchSize: 3
[TensorRT] ERROR: cuda/cudaConvolutionLayer.cpp (99) - Cudnn Error in computeScratchSize: 3
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/nvidia/Data/ningl/build/torch2trt/torch2trt/test.py", line 101, in <module>
    max_error, fps, fps_trt, ms, ms_trt = run(test)
  File "/media/nvidia/Data/ningl/build/torch2trt/torch2trt/test.py", line 30, in run
    outputs_trt = module_trt(*inputs_trt)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/nvidia/Data/ningl/build/torch2trt/torch2trt/torch2trt.py", line 213, in forward
    idx = self.engine.get_binding_index(output_name)
AttributeError: 'NoneType' object has no attribute 'get_binding_index'
```

Attach my model content:
```
class KitModel(nn.Module):

  def __init__(self):
    super(KitModel, self).__init__()

    self.conv_0 = nn.Conv2d(padding=1, dilation=(1L, 1L), in_channels=3, out_channels=32, kernel_size=(3L, 3L), stride=(1L, 1L), groups=1, bias=True)
    self.conv_1 = nn.Conv2d(padding=2, dilation=(2L, 2L), in_channels=32, out_channels=32, kernel_size=(3L, 3L), stride=(1L, 1L), groups=1, bias=True)
    self.conv_2 = nn.Conv2d(padding=4, dilation=(4L, 4L), in_channels=32, out_channels=32, kernel_size=(3L, 3L), stride=(1L, 1L), groups=1, bias=True)
    self.conv_3 = nn.Conv2d(padding=8, dilation=(8L, 8L), in_channels=32, out_channels=32, kernel_size=(3L, 3L), stride=(1L, 1L), groups=1, bias=True)
    self.conv_4 = nn.Conv2d(padding=16, dilation=(16L, 16L), in_channels=32, out_channels=32, kernel_size=(3L, 3L), stride=(1L, 1L), groups=1, bias=True)
    self.conv_5 = nn.Conv2d(padding=32, dilation=(32L, 32L), in_channels=32, out_channels=32, kernel_size=(3L, 3L), stride=(1L, 1L), groups=1, bias=True)
    self.convf_6 = nn.Conv2d(in_channels=192, out_channels=3, kernel_size=(1L, 1L), stride=(1L, 1L), groups=1, bias=True)

  def forward(self, x):
    conv_0 = self.conv_0(x)
    conv_0_activation = F.relu(conv_0)

    conv_1 = self.conv_1(conv_0_activation)
    conv_1_activation = F.relu(conv_1)

    conv_2 = self.conv_2(conv_1_activation)
    conv_2_activation = F.relu(conv_2)

    conv_3 = self.conv_3(conv_2_activation)
    conv_3_activation = F.relu(conv_3)

    conv_4 = self.conv_4(conv_3_activation)
    conv_4_activation = F.relu(conv_4)

    conv_5 = self.conv_5(conv_4_activation)
    conv_5_activation = F.relu(conv_5)

    concatenate_1 = torch.cat(
        [conv_0_activation, conv_1_activation, conv_2_activation,
         conv_3_activation, conv_4_activation, conv_5_activation],
        1)
    convf_6 = self.convf_6(concatenate_1)
    convf_6_activation = F.relu(convf_6)
    return convf_6_activation
```

**Comment by jaybdub** [comment]
Hi dummyedu,

Thanks for reaching out.  From first glance, it looks like this should work, I'll give it a test.

Can you also share what TensorRT version you have installed?

Best,
John

**Comment by dummyedu** [comment]
My TensorRT version is '5.0.6.3'

And with some more info.
1. If I remove torch.cat and convf_6. it works. 
2. If I export the model to a onnx and run with trtexec. it works.

**Comment by jaybdub** [comment]
Hi dummyedu,

I've just tested using the following code, and it worked for me

```python
model = KitModel().cuda().eval()

data = torch.randn((1, 3, 224, 224)).float().cuda()

model_trt = torch2trt(model, [data])

max_error = torch.abs(model(data) - model_trt(data)).max()

print(max_error)
```

Which reported a max error of 0.  Could you share the command you used to convert (including example data / torch2trt parameters).

My system configuration is

1. Jetson AGX Xavier (JetPack 4.2.0)
2. PyTorch 1.1
3. TensorRT 5.0.6.3
4. Python 3.6.7

I will soon validate this against JetPack 4.2.1.

Best,
John

**Comment by jaybdub** [comment]
Actually, I noticed the issue you reported when setting ``fp16_mode = True``.   The network parsed, but engine creation failed.  Did you have this flag set as well?

You said this worked with trtexec.  Could you provide the steps you took to test with ONNX / trtexec.  Most notably, did you enable fp16 mode here as well?

Best,
John

**Comment by jaybdub** [comment]
I just attempted ONNX -> trtexec.  It too seems to fail with --fp16 flag set.  

To help you immediately, I was able to convert your model (with fp16 mode), by replacing 

```python
concatenate_1 = torch.cat(
        [conv_0_activation, conv_1_activation, conv_2_activation,
         conv_3_activation, conv_4_activation, conv_5_activation],
1)
```

with 

```python
concatenate_1_a = torch.cat([conv_0_activation, conv_1_activation, conv_2_activation], 1)
concatenate_1_b = torch.cat([conv_3_activation, conv_4_activation, conv_5_activation], 1)
concatenate_1 = torch.cat([concatenate_1_a, concatenate_1_b], 1)
```

Which should be functionally equivalent.  Please let me know if this works for you.

I will continue to track this issue.

Best,
John

**Comment by jaybdub** [comment]
FYI,  I've also just implemented support for strict type constraints.  This seems to also be a suitable workaround for the issue.  You can enable this by

```python
model_trt = torch2trt.torch2trt(model, [data], fp16_mode=True, log_level=trt.Logger.INFO, strict_type_constraints=True)
```

Best,
John

**Comment by dummyedu** [comment]
Thanks for the support. Yes the problem is caused by the --fp16_mode
I followed your guide and did the test. 
It works if I set strict_type_constraints=True.
