### ISSUE TITLE
Serving with TRTIS

### ISSUE THREAD

**Issue by dhkim0225** [NVIDIA-AI-IOT/torch2trt#212]
Hello. I want to serve the model using torch2trt and tensorrt inference server. 

However, I keep getting problems when deserializing the model. 
I created a repository to reproduce this issue.
https://github.com/dhkim0225/reproduce-torch2trt-issue-212

I'm not sure but think it's because of this line.
https://github.com/NVIDIA/tensorrt-inference-server/blob/e027e9692fb74fe2af72b21f33b57373569e68d2/src/backends/tensorrt/plan_backend_factory.cc#L56

torch2trt use a namespace 'torch2trt', but initLibNvInferPlugins is only called with null namespace.

How can I use TRTIS with torch2trt?

**Comment by dhkim0225** [comment]
Hmmm.... There's also an error when I try to deserialize model with following code.

```python3
import ctypes
import tensorrt as trt


TRT_LOGGER = trt.Logger(trt.Logger.WARNING)


def load_plugins():
    ctypes.CDLL('/opt/torch2trt/libtorch2trt.so')

    registry = trt.get_plugin_registry()
    torch2trt_creators = [c for c in registry.plugin_creator_list if c.plugin_namespace == 'torch2trt']
    for c in torch2trt_creators:
        registry.register_creator(c, 'torch2trt')


def get_engine(engine_file_path):
    with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
        engine = runtime.deserialize_cuda_engine(f.read())
    return engine


if __name__ == "__main__":
    engine = get_engine('/home/model/my_model/1/model.plan')

```

```
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin interpolatetorch2trt version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (259) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
```

I pushed code to my [github](https://github.com/dhkim0225/reproduce-torch2trt-issue-212). 
Any Ideas..?

**Comment by dhkim0225** [comment]
I forked torch2trt and remove namespace.

Also Linking pytorch c10 library solved my problem.

forked torch2trt(removed namespace version) : https://github.com/dhkim0225/torch2trt.git
updated git repository(linking Dockerfile updated) : https://github.com/dhkim0225/reproduce-torch2trt-issue-212
