### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by BarryKCL** [NVIDIA-AI-IOT/torch2trt#438]
when I use torch2trt and another TensorRT engine, an illegal memory access was encountered。

**Comment by BernardinD** [comment]
@BarryKCL any progress here? Same issue for me

**Comment by Huang9495** [comment]
@BernardinD @BarryKCL This issue is resolved？

**Comment by jrb-cobot** [comment]
For me, this was because I was trying to calibrate without moving the example data to GPU.
