### ISSUE TITLE
Converting Model From DLI Course to Tensorrt

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [NVIDIA-AI-IOT/torch2trt#541]
Hi guys, I'm going through the DLI course and while running the classification model I get quite fast and accurate results (using a CSI Camera), so I decided to add another camera (USB webcam) and run inference on the 2 cameras at the same time and everything is works well except that there is allot of latency when using 2 cameras.

So I decided to optimize my model by converting it to Tensorrt and so I installed torch2trt in the container, and converted my model to tensorrt successfully using the command below:

```
from torch2trt import torch2trt
data = torch.zeros((1, 3, 224, 224)).cuda().half()
model_trt = torch2trt(model, [data], fp16_mode=True)
```

However when trying to run inference using the tensorrt model I just receive NaN values for the prediction. Any help?

Regards,
Abu

**Comment by abuelgasimsaadeldin** [comment]
@dusty-nv @jaybdub, Any help in solving this issue would be highly appreciated.  

Best,
Abu

**Comment by abuelgasimsaadeldin** [comment]
UPDATE: The solution was to use:
```
data = torch.zeros((1, 3, 224, 224)).cuda()
```

It worked fine after that but I still receive some latency when using the optimized tensorrt model when using 2 cameras, might need to think of another method.
